"""
Django settings for bookmarks project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e!r84vt(1%4p*vcqgetfqq=oh@80-$u%44oc&##s&hc3$y_j71'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'django.contrib.admin',
    'social.apps.django_app.default',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'bookmarks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmarks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
                    os.path.join(BASE_DIR, 'bookmarks', 'static'),
                )

# file directory to upload images
MEDIA_URL       = '/media/'
MEDIA_ROOT      =  os.path.join(BASE_DIR, 'media/')




from django.core.urlresolvers import reverse_lazy

LOGIN_REDIRECT_URL  = reverse_lazy('dashboard')
LOGIN_URL           = reverse_lazy('login')
LOGOUT_URL          = reverse_lazy('logout')


#smtp configuration so that django can send email

EMAIL_BACKEND       = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_HOST_USER     = 'GOOGLE_EMAIL_ADDRESS'
EMAIL_HOST_PASSWORD = 'PASS'
EMAIL_PORT          =  587
EMAIL_USE_TLS       =  True



################ custom and social Authentication #########
# checks for authentication one by one and authenticate if matches otherwise user is not authenticate and loged into the app
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',#django default authentication
    'account.authentication.EmailAuthBackend',#django custom authentication (check authentication using email)
    'social.backends.facebook.FacebookOAuth2',#django fb authentication
    'social.backends.twitter.TwitterOAuth',#django twitter authentication
    'social.backends.google.GoogleOAuth2',#django google authentication
)

## FACEBOOK
SOCIAL_AUTH_FACEBOOK_KEY    = '1962733214005088'
SOCIAL_AUTH_FACEBOOK_SECRET = '050a55f646c1a69f56d2ec9d6728781e'

# SOCIAL_AUTH_FACEBOOK_API_VERSION = '2.9'

#TwitterOAuth
SOCIAL_AUTH_TWITTER_KEY     =   'lyw5uCoQKQ9bWqsqqJjxT2LdK'
SOCIAL_AUTH_TWITTER_SECRET  =   'GGLhDPYKzLUrbCQYzAVnFlPTX0DWTnEzkiUY5ddmIcaA0A9ns0'

# Google OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '575946405484-b02db4uukmt4jb075frvv5e0h47952fr.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'sK0y1Rs-ub8RLc1ZjFQYLNKV'
''' multiple line comment use there single quores '''